"""
theme.py
--------
Shared styling, team flag emojis, and cached data loading used by every
page of the dashboard.

Architectural note: this app is READ-ONLY at runtime. It only reads:
  - outputs/simulation_results.csv  (pre-generated by main.py)
  - data/results_2026.csv           (real match results, via bracket_data.py)
  - src/tournament.py               (static GROUPS / QUARTERFINALISTS_2026)
It never trains a model or runs a simulation at request time, which keeps
it deployable on Streamlit Community Cloud's free tier with no risk of
timing out.
"""

import streamlit as st
import streamlit.components.v1 as components
import pandas as pd
from pathlib import Path

# ---------------------------------------------------------------------------
# Colours — carried over from the approved UI design
# ---------------------------------------------------------------------------
COLORS = {
    "bg": "#050A1F",
    "card": "#0F1736",
    "card_hover": "#162044",
    "nav_bg": "#121212",
    "divider": "#1E2954",
    "text_muted": "#8EA0D9",
    "text": "#FFFFFF",
    "accent": "#3B82F6",
    "gold": "#F5C518",
    "red": "#E8112D",
}

# ---------------------------------------------------------------------------
# Flag emoji for every real 2026 team (must match tournament.py's GROUPS
# spelling exactly, since that's the join key used across every page)
# ---------------------------------------------------------------------------
FLAGS = {
    "Mexico": "🇲🇽", "South Africa": "🇿🇦", "South Korea": "🇰🇷", "Czech Republic": "🇨🇿",
    "Canada": "🇨🇦", "Switzerland": "🇨🇭", "Bosnia and Herzegovina": "🇧🇦", "Qatar": "🇶🇦",
    "Brazil": "🇧🇷", "Morocco": "🇲🇦", "Haiti": "🇭🇹", "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "United States": "🇺🇸", "Australia": "🇦🇺", "Turkey": "🇹🇷", "Paraguay": "🇵🇾",
    "Germany": "🇩🇪", "Ivory Coast": "🇨🇮", "Ecuador": "🇪🇨", "Curacao": "🇨🇼",
    "Netherlands": "🇳🇱", "Japan": "🇯🇵", "Sweden": "🇸🇪", "Tunisia": "🇹🇳",
    "Belgium": "🇧🇪", "Egypt": "🇪🇬", "Iran": "🇮🇷", "New Zealand": "🇳🇿",
    "Spain": "🇪🇸", "Cape Verde": "🇨🇻", "Saudi Arabia": "🇸🇦", "Uruguay": "🇺🇾",
    "France": "🇫🇷", "Norway": "🇳🇴", "Senegal": "🇸🇳", "Iraq": "🇮🇶",
    "Argentina": "🇦🇷", "Austria": "🇦🇹", "Algeria": "🇩🇿", "Jordan": "🇯🇴",
    "Portugal": "🇵🇹", "Colombia": "🇨🇴", "DR Congo": "🇨🇩", "Uzbekistan": "🇺🇿",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Croatia": "🇭🇷", "Ghana": "🇬🇭", "Panama": "🇵🇦",
}


def flag(team: str) -> str:
    """Return the flag emoji for a team, or a blank flag if not found."""
    return FLAGS.get(team, "🏳️")


# ---------------------------------------------------------------------------
# Data loading — cached so every page load doesn't re-read the CSV
# ---------------------------------------------------------------------------
RESULTS_PATH = Path("outputs/simulation_results.csv")


@st.cache_data
def load_results() -> pd.DataFrame:
    """
    Load the pre-generated Monte Carlo forecast. Cached for the lifetime
    of the app process — this file never changes without a fresh run of
    main.py, so there's no need to re-read it on every interaction.
    """
    if not RESULTS_PATH.exists():
        st.error(
            "outputs/simulation_results.csv not found. Run main.py locally "
            "and commit that file to the repo before deploying."
        )
        st.stop()
    return pd.read_csv(RESULTS_PATH)


# ---------------------------------------------------------------------------
# CSS injection
# ---------------------------------------------------------------------------
def inject_css():
    """Apply the shared dark navy / blue / gold theme to the whole app."""
    st.markdown(
        f"""
        <style>
        .stApp {{
            background: {COLORS['bg']};
            color: {COLORS['text']};
            font-family: system-ui, -apple-system, sans-serif;
        }}

        /* Hide Streamlit's default sidebar page list entirely — replaced
           by the floating pill nav at the bottom of the page. */
        section[data-testid="stSidebar"] {{
            display: none;
        }}

        /* Leave room at the bottom so page content never sits under the
           floating nav bar. */
        .main .block-container {{
            padding-bottom: 120px;
        }}

        h1, h2, h3, h4 {{
            font-family: system-ui, -apple-system, sans-serif;
            letter-spacing: -0.3px;
        }}

        .wc-card {{
            background: {COLORS['card']};
            border: 1px solid rgba(255,255,255,0.06);
            border-radius: 18px;
            padding: 20px 22px;
            margin-bottom: 14px;
        }}

        .wc-eyebrow {{
            font-size: 11px;
            font-weight: 700;
            letter-spacing: 2px;
            text-transform: uppercase;
            color: {COLORS['red']};
            margin-bottom: 6px;
        }}

        .wc-muted {{
            color: {COLORS['text_muted']};
            font-size: 13px;
        }}

        .wc-pill {{
            display: inline-flex;
            align-items: center;
            gap: 6px;
            font-size: 12px;
            font-weight: 700;
            letter-spacing: 1px;
            padding: 5px 12px;
            border-radius: 20px;
            background: rgba(59,130,246,0.12);
            border: 1px solid rgba(59,130,246,0.3);
            color: {COLORS['accent']};
        }}
        </style>
        """,
        unsafe_allow_html=True,
    )


# ---------------------------------------------------------------------------
# Floating bottom pill navigation — replaces Streamlit's default sidebar
# page list with the mobile-app-style nav from the approved design.
# ---------------------------------------------------------------------------
_ICON_HOME = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>'

_ICON_CHART = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><line x1="12" y1="20" x2="12" y2="10"/><line x1="18" y1="20" x2="18" y2="4"/><line x1="6" y1="20" x2="6" y2="16"/></svg>'

_ICON_GLOBE = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>'

_ICON_TROPHY = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M8 21h8M12 17v4M7 4h10v5a5 5 0 0 1-10 0V4z"/><path d="M5 4H3v2a4 4 0 0 0 4 4M19 4h2v2a4 4 0 0 1-4 4"/></svg>'

_ICON_INFO = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>'

# (internal key, url path, label, icon svg)
NAV_ITEMS = [
    ("home",   "/",               "Home",          _ICON_HOME),
    ("teams",  "/All_Teams",      "All Teams",     _ICON_CHART),
    ("groups", "/Groups",         "Groups",        _ICON_GLOBE),
    ("final",  "/Path_to_Final",  "Path to Final", _ICON_TROPHY),
    ("about",  "/About",          "About",         _ICON_INFO),
]


def render_bottom_nav(active: str):
    """
    Render the floating pill navigation bar.

    Why this doesn't use st.markdown(): Streamlit wraps every st.markdown()
    block in an internal container that has a CSS `transform` applied to
    it somewhere up the ancestor chain. Per the CSS spec, any ancestor
    with a transform becomes the new "containing block" for descendant
    position:fixed elements — so a fixed-position nav rendered via
    st.markdown() never actually reaches the real page viewport; it gets
    silently boxed into that transformed container instead, with no error.

    The fix is to skip st.markdown() for this element entirely and inject
    it straight into the real document body with JavaScript, run via a
    zero-height components.html() iframe purely as a vehicle to execute
    that script. window.parent.document is the actual top-level page
    (same-origin, since it's served by the same Streamlit process), so
    position:fixed there behaves normally.

    Call this once near the top of every page (after inject_css()),
    passing which item should be highlighted as active — one of:
    "home", "teams", "groups", "final", "about".
    """
    items_html = ""
    for key, href, label, svg in NAV_ITEMS:
        is_active = key == active
        color = COLORS["accent"] if is_active else "#FFFFFF"
        bg = "#2C2C2E" if is_active else "transparent"
        items_html += (
            f'<a href="{href}" target="_self" style="text-decoration:none;">'
            f'<div style="display:flex;flex-direction:column;align-items:center;'
            f'justify-content:center;width:72px;height:64px;border-radius:28px;'
            f'background:{bg};color:{color};">'
            f'<div style="margin-bottom:3px;">{svg}</div>'
            f'<span style="font-size:10px;font-weight:600;color:{color};">{label}</span>'
            f'</div></a>'
        )

    nav_html = (
        f'<div id="wc-bottom-nav" style="position:fixed;bottom:20px;left:50%;'
        f'transform:translateX(-50%);z-index:999999;width:95%;max-width:460px;">'
        f'<nav style="display:flex;justify-content:space-between;align-items:center;'
        f'padding:8px;background:{COLORS["nav_bg"]};border-radius:40px;'
        f'border:1px solid rgba(255,255,255,0.06);'
        f'box-shadow:0 20px 50px rgba(0,0,0,0.5);">'
        f'{items_html}</nav></div>'
    )

    # Escape backticks/${{ so the HTML is safe to embed in a JS template
    # literal, then inject it into the PARENT document's <body> — not the
    # sandboxed iframe components.html normally renders into — so
    # position:fixed is relative to the real viewport.
    safe_html = nav_html.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

    injector = (
        "<script>"
        "(function() {"
        "  const doc = window.parent.document;"
        "  const old = doc.getElementById('wc-bottom-nav');"
        "  if (old) old.remove();"
        f"  const wrapper = doc.createElement('div');"
        f"  wrapper.innerHTML = `{safe_html}`;"
        "  doc.body.appendChild(wrapper.firstChild);"
        "})();"
        "</script>"
    )
    components.html(injector, height=0, width=0)


# ---------------------------------------------------------------------------
# Shared footer — copyright + license, shown at the bottom of every page's
# content (above the floating nav bar).
# ---------------------------------------------------------------------------
def render_footer():
    """Call this once at the end of every page, after all other content."""
    st.markdown(
        '<hr style="border-color:rgba(255,255,255,0.08); margin:22px 0 14px;">'
        '<p class="wc-muted" style="font-size:11px; text-align:center; line-height:1.7;">'
        "© 2026, Jerry, Inc.<br>"
        "Licensed under the GNU General Public License v3.0 — this is free software, and you "
        "are welcome to redistribute and/or modify it under the terms of that license. "
        "See the LICENSE file in this repository for the full text."
        "</p>",
        unsafe_allow_html=True,
    )
